[theme]
# Primary accent color for interactive elements.
primaryColor = "##400000s"

# Background color for the main content area.
backgroundColor = "#800000"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#400000"

# Color used for almost all text.
textColor = "#fff"